#==========================================================
#= Articoli Web Service - Versione Base
#==========================================================

server:
  port: 5051
  
spring:
  application:
    name: ArticoliWebService
#==========================================================
#= PARAMETRI DBMS POSTGRESQL 
#==========================================================
  datasource:
    initialization-mode: always
    password: 123ciao
    platform: postgres
    url: jdbc:postgresql://localhost:5433/delivery&shop
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            '[non_contextual_creation]': true
    show-sql: true
